version: "3"
services:
  main:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ROCKET_DATABASES: '{db = {url = "postgres://postgres:postgres@db:5432/postgres"}}'
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - 5000:5000
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data
volumes:
  db_volume:
