#!/bin/bash

#                                   #
# Deploys the Hack as a Service API #
#                                   #

set -e

# Error handler
trap 'echo -e "\\n-------------------- SOMETHING WENT WRONG. --------------------\\n\\nYou may need to remove ~/.haas_deploy_lock before trying again."' ERR

# Check/set deploy lock
ssh -T -i $KEY_PATH deploy@$HAAS_IP << EOF
	if [[ ! -f ~/.haas_deploy_lock ]];
	then
		# Set up stuff
		rm -rf ~/haas_api || true
		touch ~/.haas_deploy_lock
	else
		echo 'Deploy already in progress'
		exit 1
	fi
EOF

ssh -T -i $KEY_PATH deploy@$HAAS_IP << EOF
	set -e

	echo -e "\nPulling latest migrator..."
	docker pull ghcr.io/hack-as-a-service/migrator:main

	# Migrate the DB schema
	echo -e "\nMigrating database..."
	docker run --rm -e "DATABASE_URL=$DATABASE_URL" --network haas_admin ghcr.io/hack-as-a-service/migrator:main

	echo -e "\nPulling latest image..."
	docker pull ghcr.io/hack-as-a-service/api:main

	echo -e "\nCreating haas_api_next..."
	HAAS_API_NEXT=\$(docker run -d \
		--restart always \
		--env-file ~/.env \
		--network haas_admin \
		--name haas_api_next \
		-v /var/run/docker.sock:/var/run/docker.sock \
		ghcr.io/hack-as-a-service/api:main)
	
	HAAS_API_NEXT_IP=\$(docker inspect \$HAAS_API_NEXT | jq -r .[0].NetworkSettings.Networks.haas_admin.IPAddress)

	echo "New container IP: \$HAAS_API_NEXT_IP"
	
	# Wait 5 seconds for the API to start up
	echo -e "\nWaiting impatiently for HaaS to start up..."
	sleep 5

	echo -e "\nSwitching reverse proxy over to new deployment..."
	# Update Caddy config
	curl -fs -X PATCH -H "Content-Type: application/json" -d "{\"@id\": \"haas_upstream\", \"dial\": \"\$HAAS_API_NEXT_IP:5000\"}" http://localhost:2019/id/haas_upstream

	echo -e "\nRenaming containers..."
	docker rename haas_api haas_api_prev || true
	docker rename haas_api_next haas_api

	echo -e "\nWaiting to make sure all is well with the reverse proxy..."
	sleep 5

	echo -e "\nShutting down previous deployment..."
	docker stop haas_api_prev || true
	docker rm haas_api_prev || true

	# Clean up
	rm -rf ~/haas_api || true
	rm ~/.haas_deploy_lock

	echo -e "\nDeploy complete :)"
EOF
