name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.59.0"
          components: rustfmt
      - name: Format
        run: cargo fmt -- --check
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.59.0"
      - name: Build
        run: cargo build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.59.0"
          components: clippy
      - name: Lint
        run: cargo clippy -- -D warnings
  lint-docker:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:v2.9.1-debian
    name: Lint (Dockerfile)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Lint Dockerfile
        run: hadolint docker/*.Dockerfile
